package Jeux;


/**
* Jeux/Carte.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Jeux.idl
* mardi 14 juin 2016 17 h 52 CEST
*/

public final class Carte implements org.omg.CORBA.portable.IDLEntity
{
  public String valeur = null;

  public Carte ()
  {
  } // ctor

  public Carte (String _valeur)
  {
    valeur = _valeur;
  } // ctor

} // class Carte
