package Jeux;

/**
* Jeux/IConnexionRemoteHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Jeux.idl
* mardi 14 juin 2016 17 h 52 CEST
*/

public final class IConnexionRemoteHolder implements org.omg.CORBA.portable.Streamable
{
  public Jeux.IConnexionRemote value = null;

  public IConnexionRemoteHolder ()
  {
  }

  public IConnexionRemoteHolder (Jeux.IConnexionRemote initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Jeux.IConnexionRemoteHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Jeux.IConnexionRemoteHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Jeux.IConnexionRemoteHelper.type ();
  }

}
