package Jeux;


/**
* Jeux/IJoueurRemoteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Jeux.idl
* mardi 14 juin 2016 17 h 52 CEST
*/

public interface IJoueurRemoteOperations 
{
  Jeux.Joueur creerUnCompte (String pseudo, String mdp);
  String voirLeScore (Jeux.Joueur joueur);
  Jeux.Joueur[] voirClassementJoueur ();
  Jeux.Joueur[] voirJoueursConnectes ();
} // interface IJoueurRemoteOperations
