package Jeux;

/**
* Jeux/IPartieRemoteHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Jeux.idl
* mardi 14 juin 2016 17 h 52 CEST
*/

public final class IPartieRemoteHolder implements org.omg.CORBA.portable.Streamable
{
  public Jeux.IPartieRemote value = null;

  public IPartieRemoteHolder ()
  {
  }

  public IPartieRemoteHolder (Jeux.IPartieRemote initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Jeux.IPartieRemoteHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Jeux.IPartieRemoteHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Jeux.IPartieRemoteHelper.type ();
  }

}
