package Jeux;


/**
* Jeux/IPartieRemotePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Jeux.idl
* mardi 14 juin 2016 17 h 52 CEST
*/

public abstract class IPartieRemotePOA extends org.omg.PortableServer.Servant
 implements Jeux.IPartieRemoteOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("partiesEnAttente", new java.lang.Integer (0));
    _methods.put ("creerPartie", new java.lang.Integer (1));
    _methods.put ("voirJoueursEnPartie", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Jeux/IPartieRemote/partiesEnAttente
       {
         Jeux.Partie $result[] = null;
         $result = this.partiesEnAttente ();
         out = $rh.createReply();
         Jeux.listePartiesEnAttenteHelper.write (out, $result);
         break;
       }

       case 1:  // Jeux/IPartieRemote/creerPartie
       {
         int nbJoueurs = in.read_long ();
         Jeux.Partie $result = null;
         $result = this.creerPartie (nbJoueurs);
         out = $rh.createReply();
         Jeux.PartieHelper.write (out, $result);
         break;
       }

       case 2:  // Jeux/IPartieRemote/voirJoueursEnPartie
       {
         Jeux.Partie partie = Jeux.PartieHelper.read (in);
         Jeux.Joueur $result[] = null;
         $result = this.voirJoueursEnPartie (partie);
         out = $rh.createReply();
         Jeux.listeJoueursHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Jeux/IPartieRemote:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public IPartieRemote _this() 
  {
    return IPartieRemoteHelper.narrow(
    super._this_object());
  }

  public IPartieRemote _this(org.omg.CORBA.ORB orb) 
  {
    return IPartieRemoteHelper.narrow(
    super._this_object(orb));
  }


} // class IPartieRemotePOA
