package Jeux;


/**
* Jeux/listePartiesEnAttenteHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Jeux.idl
* mardi 14 juin 2016 17 h 52 CEST
*/

public final class listePartiesEnAttenteHolder implements org.omg.CORBA.portable.Streamable
{
  public Jeux.Partie value[] = null;

  public listePartiesEnAttenteHolder ()
  {
  }

  public listePartiesEnAttenteHolder (Jeux.Partie[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Jeux.listePartiesEnAttenteHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Jeux.listePartiesEnAttenteHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Jeux.listePartiesEnAttenteHelper.type ();
  }

}
