package Jeux;


/**
* Jeux/PartieHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Jeux.idl
* mardi 14 juin 2016 17 h 52 CEST
*/

abstract public class PartieHelper
{
  private static String  _id = "IDL:Jeux/Partie:1.0";

  public static void insert (org.omg.CORBA.Any a, Jeux.Partie that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Jeux.Partie extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [4];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[0] = new org.omg.CORBA.StructMember (
            "id",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[1] = new org.omg.CORBA.StructMember (
            "nbJoueurs",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[2] = new org.omg.CORBA.StructMember (
            "nbCarte",
            _tcOf_members0,
            null);
          _tcOf_members0 = Jeux.JoueurHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (Jeux.listeJoueursHelper.id (), "listeJoueurs", _tcOf_members0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "joueurs",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (Jeux.PartieHelper.id (), "Partie", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Jeux.Partie read (org.omg.CORBA.portable.InputStream istream)
  {
    Jeux.Partie value = new Jeux.Partie ();
    value.id = istream.read_long ();
    value.nbJoueurs = istream.read_long ();
    value.nbCarte = istream.read_long ();
    value.joueurs = Jeux.listeJoueursHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Jeux.Partie value)
  {
    ostream.write_long (value.id);
    ostream.write_long (value.nbJoueurs);
    ostream.write_long (value.nbCarte);
    Jeux.listeJoueursHelper.write (ostream, value.joueurs);
  }

}
